---
- name: Install docker-compose build dependencies
  ansible.builtin.package:
    name: "{{ __docker_compose_build_packages }}"
    state: present

- name: Install docker-compose
  ansible.builtin.pip:
    name: docker-compose
