---
- name: Install docker-compose build dependencies
  ansible.builtin.package:
    name: "{{ __docker_compose_build_packages }}"
    state: present

# Bug with PyYAML dependency on Cython
- name: Install PyYAML 5.3.1
  ansible.builtin.pip:
    name: "pyyaml==5.3.1"
  when:
    - ansible_os_family == "Alpine"

- name: Install docker-compose
  ansible.builtin.pip:
    name: docker-compose
