---
# Compose installation fails without this library
- name: Install libffi-dev
  apt:
    name: libffi-dev
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install docker-compose
  pip:
    name: docker-compose
