---
- name: Include system-specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: "setup-{{ ansible_os_family }}.yml"

- import_tasks: "install-pip.yml"
  when: docker_install_compose | bool or docker_install_python_library | bool

- import_tasks: "docker-python-library.yml"
  when: docker_install_python_library | bool

- import_tasks: "docker-compose.yml"
  when: docker_install_compose | bool

- import_tasks: "docker-prune.yml"
  when: docker_system_prune | bool

- import_tasks: "docker-logging.yml"
  when: docker_log_driver != "json-driver"

- include_tasks: "docker-users.yml"
  when: docker_users | length > 0
