---
- name: Update package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400

- name: Install docker
  ansible.builtin.package:
    name: "{{ docker_package }}"
    state: present
