---
- name: Restart docker
  service:
    name: "{{ docker_service }}"
    state: restarted

- name: Deprecation warning
  debug:
    msg: >-
      DEPRECATION WARNING:
      You are using on of the deprecated options in docker role.
