---
- name: Restart docker
  service:
    name: "{{ item }}"
    state: restarted
  with_items: "{{ docker_service }}"

- name: Deprecation warning
  debug:
    msg: >-
      DEPRECATION WARNING:
      You are using on of the deprecated options in docker role.
