---
- name: Converge
  hosts: all

  vars:
    docker_install_compose: true
    docker_install_python_library: true
    docker_service_state: stopped

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  tasks:
    - name: "Include docker"
      include_role:
        name: "ansible-role-docker"
