---
- name: Converge
  hosts: all

  vars:
    docker_install_compose: true
    docker_install_python_library: true

  tasks:
    - name: "Include docker"
      include_role:
        name: "ansible-role-docker"
