---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: ansible-role-docker
    image: ${MOLECULE_IMAGE:-rsprta/alpine-ansible}
    command: ''
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
