---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: ubuntu
    image: docker.io/geerlingguy/docker-ubuntu1604-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
