---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
platforms:
  # Check only these images, because docker/systemd/ansible dont
  # play well together
  - name: Ubuntu
    image: docker.io/geerlingguy/docker-ubuntu1604-ansible
    pre_build_image: true
  - name: Debian
    image: docker.io/geerlingguy/docker-debian10-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
