---
- name: Verify
  hosts: all

  tasks:
    # Systemd acts weird in containers, so we check it
    # directly, without using the service_facts
    - name: Check that Docker is enabled and stopped
      service:
        name: docker
        enabled: true
        state: stopped
      register: docker_status

    - name: Assert Docker is enabled and stopped
      assert:
        that:
          - "not docker_status.changed"

    - name: Check if docker-compose and docker python library are installed
      pip:
        name:
          - docker
          - docker-compose
      check_mode: true
      register: pip_packages

    - name: Assert that pip packages were already installed
      assert:
        that:
          - "not pip_packages.changed"
