---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all

  vars:
    test_docker_service: docker

  tasks:
    - name: Populate service facts
      service_facts:

    - name: Assert Docker is installed
      assert:
        that:
          - "ansible_facts.services.docker is defined"
