---
- name: Converge
  hosts: all

  vars:
    docker_daemon_options: {'log-driver': 'json-file'}
    docker_install_compose: true
    docker_install_python_library: true
    docker_service_state: stopped

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

  tasks:
    - name: "Include docker"
      ansible.builtin.include_role:
        name: "radek_sprta.docker"
